# Generated by Django 2.0.4 on 2018-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userask', '0003_merge_20180412_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='userask',
            name='role',
            field=models.IntegerField(choices=[(1, 'Etudiant'), (2, 'Intervenant'), (3, 'Pédagogie')], default=1, verbose_name="role de l'utilisateur"),
        ),
    ]
