# Generated by Django 2.0.4 on 2018-04-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('max_user', models.PositiveIntegerField(verbose_name="nombre d'étudiant max")),
                ('private', models.BooleanField(verbose_name='privé')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'Groupe',
            },
        ),
    ]
