# Generated by Django 2.0.4 on 2018-04-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180411_1716'),
        ('project', '0004_auto_20180411_1511'),
    ]

    operations = [
    ]
