# Generated by Django 2.0.4 on 2018-04-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_merge_20180412_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='token_used',
        ),
        migrations.AddField(
            model_name='team',
            name='token_remain',
            field=models.PositiveIntegerField(default=0, verbose_name='token restant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.IntegerField(verbose_name='nombre de jetons par groupes'),
        ),
    ]
