# Generated by Django 2.0.4 on 2018-04-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userask', '0003_merge_20180412_0721'),
        ('project', '0006_auto_20180412_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(to='userask.UserAsk', verbose_name='all users'),
        ),
        migrations.AlterField(
            model_name='team',
            name='private',
            field=models.BooleanField(default=True, verbose_name='privé'),
        ),
    ]
