# Generated by Django 2.0.4 on 2018-04-12 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_auto_20180412_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='membres du groupe'),
        ),
        migrations.AlterField(
            model_name='team',
            name='private',
            field=models.BooleanField(default=True, verbose_name='privé'),
        ),
    ]
