# Generated by Django 2.0.4 on 2018-04-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20180412_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
    ]
